const path = require('path')
console.log('yfpdfybz afqkf: ',path.basename(__filename))
console.log(path.dirname(__filename))
console.log(path.extname(__filename))
console.log(path.parse(__filename).name)
console.log(path.join(__dirname,'server','index.html'))